
server:
  port: 11000
  
spring:
  application:
      name: cloud-server
  security:
    user:
      name: root
      password: 123456
  freemarker:
    prefer-file-system-access: false
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
      config:
       label: master
       name: config-server
       server:
        git:
          uri: https://github.com/jackliul/jacliuConfig
          search-paths:
          - oms-user
          - oms-back
          username: jackliul 
          password: 13873884179ok
          
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 90000 # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: 127.0.0.1
    virtual-host-name: cloud-server
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://${eureka.instance.ip-address}:${server.port}/eureka/ #http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  file:
    logs/${spring.application.name}.log